namespace BotsSchema {
    /**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
     * and run json-schema-to-typescript to regenerate this file.
     */

    export type Engines = AwsLex | Dialogflow;
    export type AwsRegionLex = 'us-east-1' | 'eu-west-1';
    export type AwsPollyVoice =
        | 'Geraint'
        | 'Gwyneth'
        | 'Mads'
        | 'Naja'
        | 'Hans'
        | 'Marlene'
        | 'Nicole'
        | 'Russell'
        | 'Amy'
        | 'Brian'
        | 'Emma'
        | 'Raveena'
        | 'Ivy'
        | 'Joanna'
        | 'Joey'
        | 'Justin'
        | 'Kendra'
        | 'Kimberly'
        | 'Matthew'
        | 'Salli'
        | 'Conchita'
        | 'Enrique'
        | 'Miguel'
        | 'Penelope'
        | 'Chantal'
        | 'Celine'
        | 'Mathieu'
        | 'Dora'
        | 'Karl'
        | 'Carla'
        | 'Giorgio'
        | 'Mizuki'
        | 'Liv'
        | 'Lotte'
        | 'Ruben'
        | 'Ewa'
        | 'Jacek'
        | 'Jan'
        | 'Maja'
        | 'Ricardo'
        | 'Vitoria'
        | 'Cristiano'
        | 'Ines'
        | 'Carmen'
        | 'Maxim'
        | 'Tatyana'
        | 'Astrid'
        | 'Filiz'
        | 'Vicki'
        | 'Takumi'
        | 'Seoyeon'
        | 'Aditi';

    export interface Bots {
        $schema?: string;
        [k: string]: {
            name: string;
            routes: string[];
            engine: Engines;
            options?: {
                voice?: AwsPollyVoice;
                [k: string]: any;
            };
            interfaces: {
                botsocket?: BotsocketInterface;
                facebook?: FacebookInterface;
                [k: string]: any;
            };
            [k: string]: any;
        };
    }
    export interface AwsLex {
        service: 'aws-lex';
        settings: {
            botName: string;
            botAlias: string;
            awsRegion: AwsRegionLex;
        };
        [k: string]: any;
    }
    export interface Dialogflow {
        service: 'dialogflow';
        settings: {
            clientToken: string;
        };
        [k: string]: any;
    }
    export interface BotsocketInterface {}
    export interface FacebookInterface {
        verifyToken: string;
        pageToken: string;
    }
}
